//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM account does not exist, please create a ticket with EGIC to add account in CRM..
        /// </summary>
        internal static string AccountDoesNotExistinCRM {
            get {
                return ResourceManager.GetString("AccountDoesNotExistinCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {project} can’t be pushed to CRM since the account doesn’t exist in CRM. Please check your CRM settings..
        /// </summary>
        internal static string AccountNotExists {
            get {
                return ResourceManager.GetString("AccountNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountText {
            get {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air quality/.
        /// </summary>
        internal static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Projects.
        /// </summary>
        internal static string AllPrograms {
            get {
                return ResourceManager.GetString("AllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this TCO value documentation tool is to calculate the potential savings as a result of reducing scale in Ammonia Condenser. For further detail on Ammonia KM-PAC 3 Application and Best Practices Guide-Section 3.8-Refrigeration Systems, Pages 303-304. The condenser removes the heat that was absorbed in the evaporator and increased in the compressor, thus returning the ammonia back to a liquid state. Problems occur when there is a scale build-up on the outside of the tubes, inhibiting heat trans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmmoniaCalIntro {
            get {
                return ResourceManager.GetString("AmmoniaCalIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for Android App.
        /// </summary>
        internal static string AndroidScanText {
            get {
                return ResourceManager.GetString("AndroidScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Savings Type.
        /// </summary>
        internal static string AnnualSavingsTypeLabel {
            get {
                return ResourceManager.GetString("AnnualSavingsTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving this project will remove the project from the TVD Calculator application but will not impact CRM.  Contact EGIC to restore the project..
        /// </summary>
        internal static string ArchiveConfirmation {
            get {
                return ResourceManager.GetString("ArchiveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Project.
        /// </summary>
        internal static string ArchiveProgram {
            get {
                return ResourceManager.GetString("ArchiveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Project.
        /// </summary>
        internal static string ArchiveProject {
            get {
                return ResourceManager.GetString("ArchiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity - Asset Protection.
        /// </summary>
        internal static string AssetCapacity {
            get {
                return ResourceManager.GetString("AssetCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset life.
        /// </summary>
        internal static string AssetLife {
            get {
                return ResourceManager.GetString("AssetLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string AssetText {
            get {
                return ResourceManager.GetString("AssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or use averages and standards.
        /// </summary>
        internal static string AverageStandards {
            get {
                return ResourceManager.GetString("AverageStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background sync in-progress, Please try after some time.
        /// </summary>
        internal static string BackGroundSyncInProgress {
            get {
                return ResourceManager.GetString("BackGroundSyncInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Back.
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be between.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in calculation, Please try with different values..
        /// </summary>
        internal static string CalculationErrMsg {
            get {
                return ResourceManager.GetString("CalculationErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator Type: .
        /// </summary>
        internal static string CalculatorType {
            get {
                return ResourceManager.GetString("CalculatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Calculator Type.
        /// </summary>
        internal static string CalculatorType1 {
            get {
                return ResourceManager.GetString("CalculatorType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator Type.
        /// </summary>
        internal static string CalculatorTypeText {
            get {
                return ResourceManager.GetString("CalculatorTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        internal static string CalenderText {
            get {
                return ResourceManager.GetString("CalenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes and Savings.
        /// </summary>
        internal static string ChangesAndSavings {
            get {
                return ResourceManager.GetString("ChangesAndSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAllText {
            get {
                return ResourceManager.GetString("ClearAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        internal static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the CRM project.
        /// </summary>
        internal static string CmvCrmProjectLinkOpen {
            get {
                return ResourceManager.GetString("CmvCrmProjectLinkOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current CRM Project State.
        /// </summary>
        internal static string CmvCurrentProjectState {
            get {
                return ResourceManager.GetString("CmvCurrentProjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while interacting to CRM. Please try agin later..
        /// </summary>
        internal static string CmvErrorMsgConnection {
            get {
                return ResourceManager.GetString("CmvErrorMsgConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Program Info.
        /// </summary>
        internal static string CmvInfo {
            get {
                return ResourceManager.GetString("CmvInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project hasn&apos;t been pushed to CRM (OR) This project has been deleted from the CRM (OR) Some changes has been made to this scenario.
        /// </summary>
        internal static string CMVInfomationText {
            get {
                return ResourceManager.GetString("CMVInfomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Published Date.
        /// </summary>
        internal static string CmvLastPublishedDate {
            get {
                return ResourceManager.GetString("CmvLastPublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Project Information.
        /// </summary>
        internal static string CMVProjectInformationText {
            get {
                return ResourceManager.GetString("CMVProjectInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Project Name.
        /// </summary>
        internal static string CmvProjectName {
            get {
                return ResourceManager.GetString("CmvProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{project}&apos; Project can’t be pushed to CRM..
        /// </summary>
        internal static string CmvPushFailure {
            get {
                return ResourceManager.GetString("CmvPushFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{project}&apos; Project has been pushed to CRM successfully..
        /// </summary>
        internal static string CmvPushSuccess {
            get {
                return ResourceManager.GetString("CmvPushSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare states.
        /// </summary>
        internal static string CompareStatesTabName {
            get {
                return ResourceManager.GetString("CompareStatesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this TCO value documentation tool is to calculate the potential water savings as a result of increasing tower cycles. Please make sure to review scenario in the optimizer before making recommendations..
        /// </summary>
        internal static string CoolingCalIntro {
            get {
                return ResourceManager.GetString("CoolingCalIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs.
        /// </summary>
        internal static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Project.
        /// </summary>
        internal static string CreateNewProjectPage {
            get {
                return ResourceManager.GetString("CreateNewProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Project....
        /// </summary>
        internal static string CreatingProject {
            get {
                return ResourceManager.GetString("CreatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Project....
        /// </summary>
        internal static string CreatingProjectText {
            get {
                return ResourceManager.GetString("CreatingProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date can not be empty.
        /// </summary>
        internal static string CreationDateEmpty {
            get {
                return ResourceManager.GetString("CreationDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreationDateText {
            get {
                return ResourceManager.GetString("CreationDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{project}&apos; can&apos;t be pushed to CRM since the CRM account doesn&apos;t exist, please create a ticket with EGIC to add account in CRM..
        /// </summary>
        internal static string CRMAccountNotExist {
            get {
                return ResourceManager.GetString("CRMAccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{project}&apos; can&apos;t be pushed to CRM since the CRM workbook doesn&apos;t exist in the account in CRM. Please check your CRM settings..
        /// </summary>
        internal static string CRMErrorMessage {
            get {
                return ResourceManager.GetString("CRMErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {project} can’t be pushed to CRM due to insufficient permission in CRM. Please check your CRM settings..
        /// </summary>
        internal static string CrmUserDoesNotExist {
            get {
                return ResourceManager.GetString("CrmUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency:.
        /// </summary>
        internal static string CurrencyInfo {
            get {
                return ResourceManager.GetString("CurrencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyText {
            get {
                return ResourceManager.GetString("CurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency cannot be empty.
        /// </summary>
        internal static string CurrencyValidation {
            get {
                return ResourceManager.GetString("CurrencyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the selected account. Please favorite the site associated with it in Asset harvester..
        /// </summary>
        internal static string DeepLinkNoAccountAccess {
            get {
                return ResourceManager.GetString("DeepLinkNoAccountAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the selected site. Please favorite the site in Asset harvester to access it..
        /// </summary>
        internal static string DeepLinkNoSiteAccess {
            get {
                return ResourceManager.GetString("DeepLinkNoSiteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string DiscardText {
            get {
                return ResourceManager.GetString("DiscardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display In.
        /// </summary>
        internal static string DisplayIn {
            get {
                return ResourceManager.GetString("DisplayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar saved breakdown by category.
        /// </summary>
        internal static string DollarSaveBreakdownByCategory {
            get {
                return ResourceManager.GetString("DollarSaveBreakdownByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this message again..
        /// </summary>
        internal static string DoNotShow {
            get {
                return ResourceManager.GetString("DoNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project Info.
        /// </summary>
        internal static string EditProjectInfoText {
            get {
                return ResourceManager.GetString("EditProjectInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        internal static string EditProjectPage {
            get {
                return ResourceManager.GetString("EditProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Energy.
        /// </summary>
        internal static string ElectricalEnergy {
            get {
                return ResourceManager.GetString("ElectricalEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission.
        /// </summary>
        internal static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy - Electrical.
        /// </summary>
        internal static string EnergyElectrical {
            get {
                return ResourceManager.GetString("EnergyElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy - Greenhouse Gases.
        /// </summary>
        internal static string EnergyGreenhouse {
            get {
                return ResourceManager.GetString("EnergyGreenhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string EnergyTabName {
            get {
                return ResourceManager.GetString("EnergyTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy - Thermal.
        /// </summary>
        internal static string EnergyThermal {
            get {
                return ResourceManager.GetString("EnergyThermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in calculation, Please enter different values..
        /// </summary>
        internal static string Error_Calculation {
            get {
                return ResourceManager.GetString("Error_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Exchange rate (coming soon).
        /// </summary>
        internal static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature will be coming soon.
        /// </summary>
        internal static string FeatureComingSoon {
            get {
                return ResourceManager.GetString("FeatureComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be greater or equal to.
        /// </summary>
        internal static string GreaterOrEqual {
            get {
                return ResourceManager.GetString("GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data.
        /// </summary>
        internal static string HistoricalData {
            get {
                return ResourceManager.GetString("HistoricalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to determine {0}.
        /// </summary>
        internal static string HowToDetermine {
            get {
                return ResourceManager.GetString("HowToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload images with extension .jpg / .jpeg / .png only.
        /// </summary>
        internal static string ImageExtentionAlertMsg {
            get {
                return ResourceManager.GetString("ImageExtentionAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to improved.
        /// </summary>
        internal static string Improved {
            get {
                return ResourceManager.GetString("Improved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increased.
        /// </summary>
        internal static string Increased {
            get {
                return ResourceManager.GetString("Increased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for iOS App.
        /// </summary>
        internal static string iOSScanText {
            get {
                return ResourceManager.GetString("iOSScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        internal static string LastModifiedBy {
            get {
                return ResourceManager.GetString("LastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified On.
        /// </summary>
        internal static string LastModifiedOn {
            get {
                return ResourceManager.GetString("LastModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be less or equal to.
        /// </summary>
        internal static string LessOrEqual {
            get {
                return ResourceManager.GetString("LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project....
        /// </summary>
        internal static string LoadingProject {
            get {
                return ResourceManager.GetString("LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located in: .
        /// </summary>
        internal static string LocatedIn {
            get {
                return ResourceManager.GetString("LocatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions about the login, please click the instructions below..
        /// </summary>
        internal static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Logout?.
        /// </summary>
        internal static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only allowed to upload {0} images..
        /// </summary>
        internal static string MaxImagesAlertMsg {
            get {
                return ResourceManager.GetString("MaxImagesAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBack.
        /// </summary>
        internal static string MenuFeedBack {
            get {
                return ResourceManager.GetString("MenuFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPERSONATE.
        /// </summary>
        internal static string MenuImpersonate {
            get {
                return ResourceManager.GetString("MenuImpersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string MenuNewProgram {
            get {
                return ResourceManager.GetString("MenuNewProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Now.
        /// </summary>
        internal static string MenuSync {
            get {
                return ResourceManager.GetString("MenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        internal static string MoreOptionsText {
            get {
                return ResourceManager.GetString("MoreOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative values will be pushed to CRM as 0. Would you like to continue?.
        /// </summary>
        internal static string NegativeValuesInformationText {
            get {
                return ResourceManager.GetString("NegativeValuesInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is not available.
        /// </summary>
        internal static string NetworkAvailablity {
            get {
                return ResourceManager.GetString("NetworkAvailablity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Selected.
        /// </summary>
        internal static string NoneSelectedText {
            get {
                return ResourceManager.GetString("NoneSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Found.
        /// </summary>
        internal static string NoResultFound {
            get {
                return ResourceManager.GetString("NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to correct this..
        /// </summary>
        internal static string NoSoldTo_SubText {
            get {
                return ResourceManager.GetString("NoSoldTo_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EcolabGlobalIntelligenceCenter@ecolab.com.
        /// </summary>
        internal static string NoSoldToEmailId {
            get {
                return ResourceManager.GetString("NoSoldToEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sold to associated with the selected site. Please create a ticket with.
        /// </summary>
        internal static string NoSoldToMessage {
            get {
                return ResourceManager.GetString("NoSoldToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logged in user is not Authorized. Please contact the admin..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need an active Internet connection to synchronize..
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        internal static string NotNowText {
            get {
                return ResourceManager.GetString("NotNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be numeric.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CRM Project.
        /// </summary>
        internal static string OpenCMVProjectText {
            get {
                return ResourceManager.GetString("OpenCMVProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for New Project.
        /// </summary>
        internal static string PlaceHolderProjectName {
            get {
                return ResourceManager.GetString("PlaceHolderProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity.
        /// </summary>
        internal static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity Chemistry.
        /// </summary>
        internal static string ProductivityChemistry {
            get {
                return ResourceManager.GetString("ProductivityChemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity - Labor.
        /// </summary>
        internal static string ProductivityLabor {
            get {
                return ResourceManager.GetString("ProductivityLabor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity - Location.
        /// </summary>
        internal static string ProductivityLocation {
            get {
                return ResourceManager.GetString("ProductivityLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity People.
        /// </summary>
        internal static string ProductivityPeople {
            get {
                return ResourceManager.GetString("ProductivityPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity Plant.
        /// </summary>
        internal static string ProductivityPlant {
            get {
                return ResourceManager.GetString("ProductivityPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity - Product.
        /// </summary>
        internal static string ProductivityProduct {
            get {
                return ResourceManager.GetString("ProductivityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased Production.
        /// </summary>
        internal static string Profitability {
            get {
                return ResourceManager.GetString("Profitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has already been pushed to CRM. Once you push it again, all current data will be overridden. Would you like to proceed?.
        /// </summary>
        internal static string ProgramAlreadyPushedMessage {
            get {
                return ResourceManager.GetString("ProgramAlreadyPushedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Home.
        /// </summary>
        internal static string ProjectHomePage {
            get {
                return ResourceManager.GetString("ProjectHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Info.
        /// </summary>
        internal static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        internal static string ProjectInformationText {
            get {
                return ResourceManager.GetString("ProjectInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty.
        /// </summary>
        internal static string ProjectNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProjectNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name exceeds the maximum length of {0} characters.
        /// </summary>
        internal static string ProjectNameExceedsTheMaximumLengthOf_X_Characters {
            get {
                return ResourceManager.GetString("ProjectNameExceedsTheMaximumLengthOf_X_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name should be unique within the account.
        /// </summary>
        internal static string ProjectNameShouldBeUniqueWithinTheAccount {
            get {
                return ResourceManager.GetString("ProjectNameShouldBeUniqueWithinTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Project Name.
        /// </summary>
        internal static string ProjectNameText {
            get {
                return ResourceManager.GetString("ProjectNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Type a new project name.
        /// </summary>
        internal static string ProjectNameTextUWP {
            get {
                return ResourceManager.GetString("ProjectNameTextUWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Parameters.
        /// </summary>
        internal static string ProjectParameters {
            get {
                return ResourceManager.GetString("ProjectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects total sorted by.
        /// </summary>
        internal static string ProjectsCount {
            get {
                return ResourceManager.GetString("ProjectsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name, site, or calculator.
        /// </summary>
        internal static string ProjectSearchPlaceholder {
            get {
                return ResourceManager.GetString("ProjectSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed State.
        /// </summary>
        internal static string ProposedState {
            get {
                return ResourceManager.GetString("ProposedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushed To CRM.
        /// </summary>
        internal static string PushedToCmv {
            get {
                return ResourceManager.GetString("PushedToCmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing to CRM...
        /// </summary>
        internal static string PushingToCRM {
            get {
                return ResourceManager.GetString("PushingToCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push To CRM.
        /// </summary>
        internal static string PushToCMV {
            get {
                return ResourceManager.GetString("PushToCMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Has Been Saved Successfully!.
        /// </summary>
        internal static string PushToCmvInfo {
            get {
                return ResourceManager.GetString("PushToCmvInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project TCO value can be easily pushed into your CRM project..
        /// </summary>
        internal static string PushToCmvInfoSubTitle {
            get {
                return ResourceManager.GetString("PushToCmvInfoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Push To CRM&quot; feature can be found in the &quot;Save&quot; dropdown menu..
        /// </summary>
        internal static string PushToCmvInfoSubTitleNextLine {
            get {
                return ResourceManager.GetString("PushToCmvInfoSubTitleNextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know?.
        /// </summary>
        internal static string PushToCmvInfoTitle {
            get {
                return ResourceManager.GetString("PushToCmvInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to CRM.
        /// </summary>
        internal static string PushToCmvText {
            get {
                return ResourceManager.GetString("PushToCmvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reduced.
        /// </summary>
        internal static string Reduced {
            get {
                return ResourceManager.GetString("Reduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this TCO value documentation tool is to calculate the potential savings as a result of reduced corrosion retes. Controlling corrosion can significantly reduce pipe replacement costs..
        /// </summary>
        internal static string ReducedCalIntro {
            get {
                return ResourceManager.GetString("ReducedCalIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reduced emissions.
        /// </summary>
        internal static string ReducedEmissions {
            get {
                return ResourceManager.GetString("ReducedEmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        internal static string Reliability {
            get {
                return ResourceManager.GetString("Reliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity - Reliability.
        /// </summary>
        internal static string ReliabilityCapacity {
            get {
                return ResourceManager.GetString("ReliabilityCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove the Row..
        /// </summary>
        internal static string RemoveRowAlert {
            get {
                return ResourceManager.GetString("RemoveRowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Details.
        /// </summary>
        internal static string ReportDetailsTabName {
            get {
                return ResourceManager.GetString("ReportDetailsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated successfully..
        /// </summary>
        internal static string ReportGeneratedMessage {
            get {
                return ResourceManager.GetString("ReportGeneratedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Report....
        /// </summary>
        internal static string ReportGenerating {
            get {
                return ResourceManager.GetString("ReportGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields Missing.
        /// </summary>
        internal static string RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the required fields that are missing..
        /// </summary>
        internal static string RequiredFieldsMissingMessage {
            get {
                return ResourceManager.GetString("RequiredFieldsMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} Required Field(s) Left.
        /// </summary>
        internal static string RequireFieldsLeft {
            get {
                return ResourceManager.GetString("RequireFieldsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than 8 rows..
        /// </summary>
        internal static string RowsLimit {
            get {
                return ResourceManager.GetString("RowsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as New.
        /// </summary>
        internal static string SaveAsNewProject {
            get {
                return ResourceManager.GetString("SaveAsNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes before you leave the page?.
        /// </summary>
        internal static string SaveChangesMessage {
            get {
                return ResourceManager.GetString("SaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Sucessfully..
        /// </summary>
        internal static string SavedSucessfullyText {
            get {
                return ResourceManager.GetString("SavedSucessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Options.
        /// </summary>
        internal static string SaveOptionsText {
            get {
                return ResourceManager.GetString("SaveOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string SavingText {
            get {
                return ResourceManager.GetString("SavingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for Mobile App.
        /// </summary>
        internal static string ScanText {
            get {
                return ResourceManager.GetString("ScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Account.
        /// </summary>
        internal static string SearchAccount {
            get {
                return ResourceManager.GetString("SearchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Asset.
        /// </summary>
        internal static string SearchAssetText {
            get {
                return ResourceManager.GetString("SearchAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Calculator.
        /// </summary>
        internal static string SearchCalculatorText {
            get {
                return ResourceManager.GetString("SearchCalculatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Currency.
        /// </summary>
        internal static string SearchCurrency {
            get {
                return ResourceManager.GetString("SearchCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Site.
        /// </summary>
        internal static string SearchSiteText {
            get {
                return ResourceManager.GetString("SearchSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Value Category.
        /// </summary>
        internal static string SearchValueCategoryText {
            get {
                return ResourceManager.GetString("SearchValueCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Account.
        /// </summary>
        internal static string SelectAccountText {
            get {
                return ResourceManager.GetString("SelectAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an [Asset].
        /// </summary>
        internal static string SelectAsset {
            get {
                return ResourceManager.GetString("SelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Asset.
        /// </summary>
        internal static string SelectAssetText {
            get {
                return ResourceManager.GetString("SelectAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Calculator Type.
        /// </summary>
        internal static string SelectCalculatorTypeText {
            get {
                return ResourceManager.GetString("SelectCalculatorTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Site.
        /// </summary>
        internal static string SelectSite {
            get {
                return ResourceManager.GetString("SelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Site.
        /// </summary>
        internal static string SelectSiteText {
            get {
                return ResourceManager.GetString("SelectSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Account.
        /// </summary>
        internal static string SelectTheAccount {
            get {
                return ResourceManager.GetString("SelectTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Calculator Type.
        /// </summary>
        internal static string SelectTheCalculatorType {
            get {
                return ResourceManager.GetString("SelectTheCalculatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site and Context.
        /// </summary>
        internal static string SiteAndContextText {
            get {
                return ResourceManager.GetString("SiteAndContextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SiteText {
            get {
                return ResourceManager.GetString("SiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator Type.
        /// </summary>
        internal static string SortByCalculatorType {
            get {
                return ResourceManager.GetString("SortByCalculatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string SortByProjectName {
            get {
                return ResourceManager.GetString("SortByProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Viewed.
        /// </summary>
        internal static string SortByRecentlyViewed {
            get {
                return ResourceManager.GetString("SortByRecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortByText {
            get {
                return ResourceManager.GetString("SortByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing data....
        /// </summary>
        internal static string SynchronizingData {
            get {
                return ResourceManager.GetString("SynchronizingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string SystemOffline {
            get {
                return ResourceManager.GetString("SystemOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string SystemOnline {
            get {
                return ResourceManager.GetString("SystemOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Energy.
        /// </summary>
        internal static string ThermalEnergy {
            get {
                return ResourceManager.GetString("ThermalEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields missing.
        /// </summary>
        internal static string TitleRequiredFields {
            get {
                return ResourceManager.GetString("TitleRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Savings:  .
        /// </summary>
        internal static string TotalSavingsText {
            get {
                return ResourceManager.GetString("TotalSavingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value Saved.
        /// </summary>
        internal static string TotalValueSaved {
            get {
                return ResourceManager.GetString("TotalValueSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get User details. Retry count:-.
        /// </summary>
        internal static string txt_Retry_GetUser {
            get {
                return ResourceManager.GetString("txt_Retry_GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Account.
        /// </summary>
        internal static string txtAccount {
            get {
                return ResourceManager.GetString("txtAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Description can not be more than 2000 characters..
        /// </summary>
        internal static string txtAdditionalDescriptionError {
            get {
                return ResourceManager.GetString("txtAdditionalDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Project Name.
        /// </summary>
        internal static string txtProjectName {
            get {
                return ResourceManager.GetString("txtProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the required details.
        /// </summary>
        internal static string txtRequiredFields {
            get {
                return ResourceManager.GetString("txtRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Site.
        /// </summary>
        internal static string txtSearchSite {
            get {
                return ResourceManager.GetString("txtSearchSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string txtSite {
            get {
                return ResourceManager.GetString("txtSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unsaved data in the application.
        /// </summary>
        internal static string UnsavedData {
            get {
                return ResourceManager.GetString("UnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated:.
        /// </summary>
        internal static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Category.
        /// </summary>
        internal static string ValueCategoryText {
            get {
                return ResourceManager.GetString("ValueCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your inputs.
        /// </summary>
        internal static string VerifyInputs {
            get {
                return ResourceManager.GetString("VerifyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        internal static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Solid.
        /// </summary>
        internal static string WasteSolid {
            get {
                return ResourceManager.GetString("WasteSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string WaterTabName {
            get {
                return ResourceManager.GetString("WaterTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count should be less or equal to .
        /// </summary>
        internal static string WordCount {
            get {
                return ResourceManager.GetString("WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
